### ISSUE TITLE
Duplicate record Worldwound Incursion

### ISSUE THREAD

**Issue by Auspician** [shadowchemosh/HL-Pack-Basic#15] opened 2015-02-15 05:28 UTC
When loading the Basic Pack and the GM Mythic Pack there is a duplicate record issue. Here is the exact text of the error:

File: COM_BasicPack_AP073 - The Worldwound Incursion.user (line 72) - Thing - Duplicate record encountered ('pAP73Wards')
File: COM_GMMythicPack_AP073 - The Worldwound Incursion.user (line 4) - Thing - Duplicate record encountered ('pAP73BrkLg')

**Comment by Auspician** [comment] 2015-02-15 05:36
This seems to be fixed when you don't have the Basic Pack installed as well (which is pointless as it is already included in the others packs, but that information is not immediately accessible through Hero Lab so it still is likely worth fixing). Low priority.

**Comment by shadowchemosh** [comment] 2015-02-15 05:50
So this goes back to a "load" issue with the installer not the files themselves. Both the GM/Mythic Pack can play perfectly fine together on the same computer. This is proven by the very fact that the Basic Pack is inside the GM Pack so that sort of proves they can play together. The issue is in the installer and on some computers it requires multiple installs to get all the files moved over correctly. I am going to assume you deleted the Basic Pack and then reinstalled the GM Pack again to get it work. There for installing the GM Pack multiple times.

Colen at LW has asked that anyone with these 'Duplicate' install issues please email LW support so they can work with you in debugging the issue. support@wolflair.com

**Comment by shadowchemosh** [comment] 2015-02-15 05:54
P.S. - Right now only the GM Pack and GM Mythic Pack will have problems on the iPad ONLY!  On Windows/Mac you can easily install all the packs without issues.  The only issue will be if you don't have the Official Licenses required for the Packs. =)  By the end of this weekend even the GM Pack and the GM Mythic Pack will be able to exist on together on the iPad.

**Comment by shadowchemosh** [comment] 2015-02-22 18:28
So this issue should be working now and have not heard anything in awhile.  So assuming all is good and closing out the ticket.

**Closed by shadowchemosh** 2015-02-22 18:28 UTC

**Comment by Auspician** [comment] 2015-02-22 20:16
Sounds good. Only installing the Pathfinder GM Mythic Pack (and not the Basic Pack) removes the issue. I'm not sure about running them together, but since that isn't really necessary I don't see a problem. Keep up your amazing work!
